name: vivo_app
description: "GitHub User Search - A Flutter app to search GitHub users"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.1
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  uuid: ^4.5.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  checks: ^0.3.1
  pretty_dio_logger: ^1.4.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
